# Node-specific module: caja1
node.roles=pos
node.profile=rif
machine.hostname=Caja 1
machine.printer=Not defined
machine.scale=Not defined
machine.scanner=Not defined

# Database/profile specialization for this node.
database.name=kylgis
