# Node-specific module: caja2
node.roles=pos
node.profile=plataformas
machine.hostname=Caja 2
machine.printer=Not defined

# Database/profile specialization for this node.
database.name=plataformasdigitales
