//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.Customers.Reports.Vouchers");
report.setReport("/com/mx/kylgis/pos/reports/customers_vouchers");
report.setResourceBundle("com/mx/kylgis/pos/reports/customers_messages");

report.setSentence("SELECT customers.name AS CNAME, " +
       "vouchers.voucher_number AS VNUM, " +
       "vouchers.amount AS VAMOUNT, " +
       "vouchers.status AS VSTATUS, " +
       "payments.total AS TOTAL, " +
       "tickets.ticketid AS TICKETID, " +
       "receipts.datenew AS TDATE " +
"FROM (((tickets tickets " +
        "INNER JOIN receipts receipts " +
           "ON (tickets.id = receipts.id)) " +
       "INNER JOIN payments payments " +
          "ON     (payments.receipt = receipts.id) " +
             "AND (tickets.id = payments.receipt)) " +
      "INNER JOIN vouchers vouchers " +
         "ON (payments.voucher = vouchers.voucher_number)) " +
     "INNER JOIN customers customers " +
        "ON (tickets.customer = customers.id) " +
"WHERE ?(QBF_FILTER) " +
"ORDER BY customers.name ");

report.addParameter("ID");
report.addParameter("NAME");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsCustomer());

report.addField("CNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("VNUM", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("VAMOUNT", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("VSTATUS", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TOTAL", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TICKETID", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TDATE", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);

report;