//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.InventoryDiff");
report.setReport("/com/mx/kylgis/pos/reports/inventory_diff");
report.setResourceBundle("com/mx/kylgis/pos/reports/inventory_messages");

report.setSentence("SELECT " +
                    "locations.ID AS LOCATIONID, locations.NAME AS LOCATIONNAME, " +
                    "products.REFERENCE, products.NAME, " +
                    "products.CATEGORY, categories.NAME AS CATEGORYNAME, " +
                    "products.SUPPLIER, " +
                    "SUM(CASE WHEN stockdiary.UNITS <0 THEN stockdiary.UNITS ELSE 0 END) AS UNITSOUT, " +
                    "SUM(CASE WHEN stockdiary.UNITS <0 THEN stockdiary.UNITS * stockdiary.PRICE ELSE 0 END) AS TOTALOUT, " +
                    "SUM(CASE WHEN stockdiary.UNITS >=0 THEN stockdiary.UNITS ELSE 0 END) AS UNITSIN, " +
                    "SUM(CASE WHEN stockdiary.UNITS >=0 THEN stockdiary.UNITS * stockdiary.PRICE ELSE 0 END) AS TOTALIN, " +
                    "SUM(stockdiary.UNITS) AS UNITSDIFF, " +
                    "SUM(stockdiary.UNITS * stockdiary.PRICE) AS TOTALDIFF " +
                "FROM stockdiary JOIN locations ON stockdiary.LOCATION = locations.ID, " +
                    "products LEFT OUTER JOIN categories ON products.CATEGORY = categories.ID " +
                "WHERE products.ID = stockdiary.PRODUCT " +
                "AND ?(QBF_FILTER) " +
                "GROUP BY locations.ID, locations.NAME, products.REFERENCE, products.NAME, products.CATEGORY, categories.NAME " +
                "ORDER BY locations.ID, categories.NAME, products.NAME");

report.addParameter("stockdiary.DATENEW");
report.addParameter("stockdiary.DATENEW");

paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();
paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
// JG - 8 Jan 14 paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());
report.addQBFFilter(paramdates);

report.addParameter("locations.ID");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsLocationWithFirst());

report.addParameter("stockdiary.REASON");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsReason());

report.addField("LOCATIONID", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("LOCATIONNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("REFERENCE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("NAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CATEGORY", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CATEGORYNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("SUPPLIER", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("UNITSOUT", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TOTALOUT", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("UNITSIN", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TOTALIN", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("UNITSDIFF", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TOTALDIFF", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;
