//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.Inventory.Reports.Diary");
report.setReport("/com/mx/kylgis/pos/reports/inventory_diary");
report.setResourceBundle("com/mx/kylgis/pos/reports/inventory_messages");

report.setSentence("SELECT "
            + "TIMESTAMP(stockdiary.datenew), stockdiary.reason, stockdiary.supplierdoc, "
            + "sum(stockdiary.units), stockdiary.price, "
            + "sum(stockdiary.UNITS * stockdiary.PRICE) AS TOTALP, "
            + "suppliers.name AS SUPPLIERNAME, "
            + "products.name, products.reference, products.code, "
            + "locations.name "
        + "FROM ((stockdiary stockdiary "
            + "INNER JOIN locations locations "
                + "ON (stockdiary.location = locations.id)) "
            + "INNER JOIN products products "
                + "ON (stockdiary.product = products.id)) "
            + "LEFT OUTER JOIN suppliers suppliers "
                + "ON (products.supplier = suppliers.id) "
        + "WHERE VISIBLE = " + app.getSession().DB.TRUE() + " AND ?(QBF_FILTER) " 
        + "GROUP BY locations.name, stockdiary.reason, stockdiary.datenew, products.name");

report.addParameter("stockdiary.DATENEW");
report.addParameter("stockdiary.DATENEW");
paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();
paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());
report.addQBFFilter(paramdates);

report.addParameter("stockdiary.REASON");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsReason());

report.addParameter("suppliers.ID");
report.addParameter("suppliers.NAME");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsSuppliers());

report.addField("DATENEW", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("REASON", com.mx.kylgis.pos.data.loader.Datas.INT);
report.addField("SUPPLIERDOC", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("UNITS", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("PRICE", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TOTALP", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("SUPPLIERNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("PRODUCTNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("REFERENCE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CODE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("LOCATION", com.mx.kylgis.pos.data.loader.Datas.STRING);

report;