//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.ProductLabels");
report.setReport("/com/mx/kylgis/pos/reports/labels_product");
report.setResourceBundle("com/mx/kylgis/pos/reports/labels_messages");

report.setSentence("SELECT " +
                        "products.ID, products.REFERENCE, products.CODE, products.CODETYPE, " +
                        "products.NAME, products.PRICEBUY, " +
                        "products.PRICESELL, T.ID AS TAX, T.RATE + 1 AS TAXRATE, " +
                        "categories.ID AS CATEGORY, categories.NAME AS CATEGORYNAME, " +
                        "products.SUPPLIER " +
                    "FROM ((products products " +
                        "INNER JOIN stockcurrent stockcurrent " +
                            "ON (products.ID = stockcurrent.PRODUCT)) " +
                        "LEFT OUTER JOIN categories categories " +
                            "ON (products.CATEGORY = categories.ID)) " +
                        "LEFT OUTER JOIN taxes T " +
                            "ON (products.TAXCAT = T.ID) " +
                    "WHERE ?(QBF_FILTER) " +
                    "GROUP BY products.REFERENCE " +
                    "ORDER BY categories.NAME, products.NAME");

report.addParameter("products.NAME");
report.addParameter("products.CATEGORY");
report.addParameter("products.CODE");
report.addQBFFilter(new com.mx.kylgis.pos.ticket.ProductFilter4());

report.addField("ID", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("REFERENCE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CODE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CODETYPE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("NAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("PRICEBUY", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("PRICESELL", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TAX", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TAXRATE", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("CATEGORY", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CATEGORYNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("SUPPLIER", com.mx.kylgis.pos.data.loader.Datas.STRING);

report;