//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.TimeSeriesProduct");
report.setReport("/com/mx/kylgis/pos/reports/sales_chart_timeseriesproduct");
report.setResourceBundle("com/mx/kylgis/pos/reports/sales_messages");

report.setSentence("SELECT "
        + "products.code AS code, "
        + "products.codetype AS codetype, "
        + "products.reference AS prodref, "
        + "products.name AS prodname, "
        + "DATE(receipts.datenew) AS datesold, "
        + "receipts.datenew AS datestamp, "
        + "count(ticketlines.UNITS) AS unitssold "
    + "FROM ((ticketlines ticketlines "
        + "INNER JOIN products products "
            + "ON (ticketlines.PRODUCT = products.id)) "
        + "INNER JOIN tickets tickets "
           + "ON (TICKET = tickets.id)) "
        + "INNER JOIN receipts receipts "
            + "ON (tickets.id = receipts.id) "
    + "WHERE ?(QBF_FILTER) "
    + "GROUP BY DATE(receipts.datenew) "
    + "ORDER BY 5 ASC");

report.addParameter("receipts.DATENEW");
report.addParameter("receipts.DATENEW");

paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();

paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
// JG - 8 Jan 14 paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());

report.addQBFFilter(paramdates);

report.addParameter("products.NAME");
//report.addParameter("products.ID");
report.addParameter("products.CATEGORY");
report.addParameter("products.PRICEBUY");
report.addParameter("products.PRICESELL");
report.addParameter("products.CODE");

report.addQBFFilter(new com.mx.kylgis.pos.ticket.ProductFilter2());

report.addField("code", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("codetype", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("prodref", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("prodname", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("datesold", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("datestamp", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("unitssold", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;