//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.Closing");
report.setReport("/com/mx/kylgis/pos/reports/sales_closedpos");
report.setResourceBundle("com/mx/kylgis/pos/reports/sales_messages");

report.setSentence("SELECT " + 
                    "closedcash.HOST, " +
                    "closedcash.HOSTSEQUENCE, " +
                    "closedcash.MONEY, " +
                    "closedcash.DATESTART, " +
                    "closedcash.DATEEND, " +
                    "payments.PAYMENT, " +
                    "SUM(payments.TOTAL) AS TOTAL " +
                    "FROM closedcash, payments, receipts " +
                    "WHERE closedcash.MONEY = receipts.MONEY AND payments.RECEIPT = receipts.ID AND ?(QBF_FILTER) " +
                    "GROUP BY closedcash.HOST, closedcash.HOSTSEQUENCE, closedcash.MONEY, closedcash.DATESTART, closedcash.DATEEND, payments.PAYMENT " +
                    "ORDER BY closedcash.HOST, closedcash.HOSTSEQUENCE");

report.addParameter("closedcash.DATEEND");
report.addParameter("closedcash.DATEEND");

paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();
paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());

report.addQBFFilter(paramdates);

report.addField("HOST", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("HOSTSEQUENCE", com.mx.kylgis.pos.data.loader.Datas.INT);
report.addField("MONEY", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("DATESTART", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("DATEEND", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("PAYMENT", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TOTAL", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;
