//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.PaymentReport");
report.setReport("/com/mx/kylgis/pos/reports/sales_payments");
report.setResourceBundle("com/mx/kylgis/pos/reports/sales_messages");

report.setSentence("SELECT " +
    "LEFT(DATE(receipts.DATENEW),10) AS GROUPDATE, " +
    "receipts.DATENEW, " +
    "payments.PAYMENT, " +
    "payments.NOTES, " +
    "payments.TOTAL " +
"FROM payments,receipts " +
"WHERE payments.RECEIPT = receipts.ID AND ?(QBF_FILTER) " +
"ORDER BY receipts.DATENEW");

report.addParameter("receipts.DATENEW");
report.addParameter("receipts.DATENEW");
//report.addParameter("payments.PAYMENT");

paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();

paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
// JG - 8 Jan 14 paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());

report.addQBFFilter(paramdates);

report.addField("GROUPDATE", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("DATENEW", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("PAYMENT", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("NOTES", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TOTAL", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;