//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.ExtendedCashRegisterLog");
report.setReport("/com/mx/kylgis/pos/reports/sales_extendedcashregisterlog");
report.setResourceBundle("com/mx/kylgis/pos/reports/sales_messages");

report.setSentence("SELECT " +
        "tickets.TICKETID AS TICKET_NO, " +
        "receipts.DATENEW AS TICKET_DATE, " +
        "people.NAME AS PERSON, " +
        "payments.PAYMENT AS PAYMENT, " +
        "payments.NOTES, " +
        "payments.TOTAL AS MONEY, " +
        "payments.TENDERED " +
    "FROM ((tickets tickets " +
        "LEFT OUTER JOIN people people ON (tickets.PERSON = people.ID)) " +
        "RIGHT OUTER JOIN receipts receipts ON (receipts.ID = tickets.ID)) " +
        "LEFT OUTER JOIN payments payments ON (receipts.ID = payments.RECEIPT) " +
    "WHERE ?(QBF_FILTER) " +
        "ORDER BY TICKET_DATE ASC");

report.addParameter("receipts.DATENEW");
report.addParameter("receipts.DATENEW");

paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();
paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());
report.addQBFFilter(paramdates);

report.addParameter("people.ID");
report.addParameter("people.NAME");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsUser());

report.addField("TICKET_NO", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TICKET_DATE", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("PERSON", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("PAYMENT", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("NOTES", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("MONEY", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TENDERED", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

return report;