//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
// *** NOT SUITABLE FOR DERBY DB'S***

report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.ExtendedByProducts");
report.setReport("/com/mx/kylgis/pos/reports/sales_extproducts");
report.setResourceBundle("com/mx/kylgis/pos/reports/sales_messages");

report.setSentence("SELECT " +
//        "customers.ID, customers.name AS CUSTname, " +
        "customers.name AS CUSTname, " +
        "categories.NAME AS CATname, " +
        "products.REFERENCE AS PRODref, products.NAME AS PRODname, " +
//        "receipts.datenew, " +
        "SUM(ticketlines.units) AS TOTALunits, " +
        "SUM(ticketlines.UNITS * ticketlines.PRICE) AS TOTALnet, " +
        "SUM((ticketlines.PRICE * taxes.RATE) * ticketlines.UNITS) AS TOTALtax, " +
        "SUM((ticketlines.PRICE * ticketlines.UNITS) + ((ticketlines.PRICE * taxes.RATE) * ticketlines.UNITS)) AS TOTALgross " +
    "FROM (((((products products INNER JOIN categories categories " +
            "ON (products.CATEGORY = categories.ID)) " +
            "INNER JOIN ticketlines ticketlines ON (ticketlines.product = products.ID)) " +
            "INNER JOIN tickets tickets ON (ticketlines.ticket = tickets.id)) " +
            "INNER JOIN customers customers ON (tickets.customer = customers.id)) " +
            "INNER JOIN receipts receipts ON (tickets.id = receipts.id)) " +
            "INNER JOIN taxes taxes ON (ticketlines.taxid = taxes.id) " +
    "WHERE ?(QBF_FILTER) " +
    "GROUP BY customers.name, categories.NAME, products.REFERENCE " +
    "ORDER BY CUSTname ASC, CATname ASC, PRODname ASC"); 

report.addParameter("customers.ID");
 report.addParameter("customers.NAME");
 report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsCustomer());

 report.addParameter("receipts.DATENEW");
 report.addParameter("receipts.DATENEW");
 paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();
 paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
 paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());
 report.addQBFFilter(paramdates);

report.addParameter("products.NAME");
report.addParameter("products.PRICEBUY");
report.addParameter("products.PRICESELL");
report.addParameter("products.CATEGORY");
report.addParameter("products.CODE");
report.addQBFFilter(new com.mx.kylgis.pos.ticket.ProductFilter());

report.addField("CUSTname", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CATname", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("PRODref", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("PRODname", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TOTALunits", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TOTALnet", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TOTALtax", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TOTALgross", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;