//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.ProductSales");
report.setReport("/com/mx/kylgis/pos/reports/sales_chart_productsales");
report.setResourceBundle("com/mx/kylgis/pos/reports/sales_messages");

report.setSentence(
            "SELECT " +
            "products.REFERENCE, " +
            "products.NAME, " +
            "SUM(ticketlines.UNITS) AS UNITS, " +
            "SUM(ticketlines.UNITS * ticketlines.PRICE) AS TOTAL " +
            "FROM receipts, tickets, ticketlines, products " +
            "WHERE receipts.ID = tickets.ID AND tickets.ID = ticketlines.TICKET AND ticketlines.PRODUCT = products.ID AND ?(QBF_FILTER) " +
            "GROUP BY products.REFERENCE, products.NAME " +
            "ORDER BY products.NAME");

report.addParameter("receipts.DATENEW");
report.addParameter("receipts.DATENEW");

paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();

paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
// JG - 8 Jan 14 paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());

report.addQBFFilter(paramdates);
report.addParameter("products.NAME");
report.addParameter("products.PRICEBUY");
report.addParameter("products.PRICESELL");
report.addParameter("products.CATEGORY");
report.addParameter("products.CODE");
report.addQBFFilter(new com.mx.kylgis.pos.ticket.ProductFilter());

report.addField("REFERENCE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("NAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("UNITS", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TOTAL", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;
