//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.Suppliers.Reports.List");
report.setReport("/com/mx/kylgis/pos/reports/suppliers_list");
report.setResourceBundle("com/mx/kylgis/pos/reports/suppliers_messages");

report.setSentence("SELECT TAXID, NAME, FIRSTNAME, LASTNAME,ADDRESS,ADDRESS2,CITY,POSTAL,PHONE,EMAIL " +
                   "FROM suppliers " +
                   "WHERE VISIBLE = " + app.getSession().DB.TRUE() + " AND ?(QBF_FILTER)" +
                   "ORDER BY NAME ");

report.addParameter("TAXID");
report.addParameter("NAME");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsSuppliers());

report.addField("TAXID", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("NAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("FIRSTNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("LASTNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("ADDRESS", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("ADDRESS2", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CITY", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("POSTAL", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("PHONE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("EMAIL", com.mx.kylgis.pos.data.loader.Datas.STRING);

report;