//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.Suppliers.Reports.Products");
report.setReport("/com/mx/kylgis/pos/reports/suppliers_products");
report.setResourceBundle("com/mx/kylgis/pos/reports/suppliers_messages");

report.setSentence("SELECT "
                    + "suppliers.name AS SUPPLIERNAME, "
                    + "products.REFERENCE, "
                    + "products.CODE, "
                    + "products.NAME AS PRODUCTNAME, "
                    + "products.PRICEBUY, "
                    + "products.PRICESELL "
                + "FROM (suppliers suppliers "
                        + "INNER JOIN products products "
                        + "ON (suppliers.id = products.SUPPLIER)) "
                + "WHERE ?(QBF_FILTER)" 
                + "ORDER BY SUPPLIERNAME, PRODUCTNAME");

report.addParameter("SUPPLIERS.ID");
report.addParameter("SUPPLIERS.NAME");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsSuppliers());

report.addField("SUPPLIERNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("REFERENCE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CODE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("PRODUCTNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("PRICEBUY", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("PRICESELL", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);


report;