//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.Suppliers.Reports.Diary");
report.setReport("/com/mx/kylgis/pos/reports/suppliers_diary");
report.setResourceBundle("com/mx/kylgis/pos/reports/suppliers_messages");

report.setSentence("SELECT "
                    + "suppliers.NAME, "
                    + "stockdiary.datenew, "
                    + "products.NAME, products.REFERENCE, "
                    + "stockdiary.units, stockdiary.price, "
                    + "stockdiary.supplierdoc, stockdiary.reason, "
                    + "sum(stockdiary.units * stockdiary.price) AS totalP " 
                + "FROM (stockdiary stockdiary "
                        + "INNER JOIN suppliers suppliers "
                        + "ON (stockdiary.supplier = suppliers.id)) "
                        + "INNER JOIN products products "
                        + "ON (stockdiary.product = products.ID) "
                + "WHERE VISIBLE = " + app.getSession().DB.TRUE() + " AND ?(QBF_FILTER)" 
                    + "GROUP BY suppliers.id, stockdiary.id, products.id " 
                + "ORDER BY suppliers.NAME, stockdiary.datenew DESC");

report.addParameter("suppliers.ID");
report.addParameter("suppliers.NAME");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsSuppliers());

report.addParameter("stockdiary.REASON");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsReason());

report.addParameter("stockdiary.DATENEW");
report.addParameter("stockdiary.DATENEW");
paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();

paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());
report.addQBFFilter(paramdates);

report.addParameter("products.NAME");
report.addParameter("products.PRICEBUY");
report.addParameter("products.PRICESELL");
report.addParameter("products.CATEGORY");
report.addParameter("products.CODE");
report.addQBFFilter(new com.mx.kylgis.pos.ticket.ProductFilter());

report.addField("SUPPLIERNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("DATENEW", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("PRODUCTNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("REFERENCE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("UNITS", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("PRICE", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("SUPPLIERDOC", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("REASON", com.mx.kylgis.pos.data.loader.Datas.INT);
report.addField("TOTALP", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;