//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.InventoryQtyUpdate");
report.setReport("/com/mx/kylgis/pos/reports/tools_inventoryqtyupdate");
report.setResourceBundle("com/mx/kylgis/pos/reports/tools_messages");

report.setSentence("SELECT ROWNUMBER, CSVERROR, REFERENCE, CODE, PRICEBUY " +
        "FROM csvimport " +
        "WHERE CSVERROR = 'Qty update'" +
        "ORDER BY ROWNUMBER");

report.addField("rownumber", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("csverror", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("reference", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("code", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("pricebuy", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;