//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.UpdatedPrices");
report.setReport("/com/mx/kylgis/pos/reports/tools_updatedprices");
report.setResourceBundle("com/mx/kylgis/pos/reports/tools_messages");

report.setSentence("SELECT csvimport.REFERENCE, csvimport.CODE,"+
       "csvimport.NAME, csvimport.PRICEBUY,csvimport.PRICESELL,csvimport.PREVIOUSBUY,csvimport.PREVIOUSSELL"+
        " FROM csvimport WHERE csvimport.CSVERROR='Updated Price Details' ");


report.addField("REFERENCE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CODE", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("NAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("PRICEBUY", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("pricesell", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("previousbuy", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("previoussell", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;