//    uniCenta oPOS - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2018 uniCenta & previous Openbravo POS works
//    https://unicenta.com
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.Customers.Reports.Cards");
report.setReport("/com/openbravo/reports/customers_cards");
report.setResourceBundle("com/openbravo/reports/customers_messages");

report.setSentence("SELECT ID, TAXID, NAME, CARD, " +
                    "FIRSTNAME, LASTNAME, " +
                    "ADDRESS, ADDRESS2, CITY, POSTAL, " +
                    "IMAGE " +
                   "FROM customers " +
                   "WHERE VISIBLE = " + app.getSession().DB.TRUE() + " AND ?(QBF_FILTER)");

report.addParameter("ID");
report.addParameter("NAME");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsCustomer());

report.addField("ID", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TAXID", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("NAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CARD", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("FIRSTNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("LASTNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("ADDRESS", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("ADDRESS2", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("CITY", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("POSTAL", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("IMAGE", com.mx.kylgis.pos.data.loader.Datas.IMAGE);

report;