//    uniCenta oPOS - Touch Friendly Point Of Sale
//    Copyright (c) 2009-2018 uniCenta & previous Openbravo POS works
//    https://unicenta.com
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.PaymentReport");
report.setReport("/com/openbravo/reports/sales_payments");
report.setResourceBundle("com/openbravo/reports/sales_messages");

report.setSentence("SELECT " +
    "LEFT(DATE(receipts.DATENEW),10) AS GROUPDATE, " +
    "receipts.DATENEW, " +
    "payments.PAYMENT, " +
    "payments.NOTES, " +
    "payments.TOTAL " +
"FROM payments,receipts " +
"WHERE payments.RECEIPT = receipts.ID AND ?(QBF_FILTER) " +
"ORDER BY receipts.DATENEW");

report.addParameter("receipts.DATENEW");
report.addParameter("receipts.DATENEW");
//report.addParameter("payments.PAYMENT");

paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();

paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
// JG - 8 Jan 14 paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());

report.addQBFFilter(paramdates);

report.addField("GROUPDATE", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("DATENEW", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("PAYMENT", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("NOTES", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TOTAL", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;
