//    uniCenta oPOS - touch friendly EPoS
//    Copyright (c) 2009-2018 uniCenta & previous Openbravo POS works
//    https://unicenta.com
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.ReportTaxes");
report.setReport("/com/openbravo/reports/sales_taxes");
report.setResourceBundle("com/openbravo/reports/sales_messages");

report.setSentence(
                "SELECT taxcategories.ID AS TAXID, taxcategories.NAME AS TAXNAME, " +
                    "ROUND(SUM(taxlines.AMOUNT),2) AS TOTALTAXES, " +
                    "ROUND(SUM(taxlines.BASE),2) AS TOTALBASE " +
                "FROM receipts, taxlines, taxes, taxcategories " + 
                "WHERE receipts.ID = taxlines.RECEIPT AND taxlines.TAXID = taxes.ID AND taxes.CATEGORY = taxcategories.ID " +
                "AND ?(QBF_FILTER) " +
                "GROUP BY taxcategories.ID,  taxcategories.NAME");

report.addParameter("receipts.DATENEW");
report.addParameter("receipts.DATENEW");

paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();

paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
// JG - 8 Jan 14 paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());


report.addQBFFilter(paramdates);

report.addField("TAXID", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TAXNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("TOTALTAXES", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("TOTALBASE", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;