//   uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>

report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.NewProducts");
report.setReport("/com/openbravo/reports/tools_newproducts");
report.setResourceBundle("com/openbravo/reports/tools_messages");

report.setSentence("SELECT "
        + "csvimport.REFERENCE, csvimport.CODE, csvimport.NAME, "
        + "csvimport.PRICEBUY, csvimport.PRICESELL, csvimport.CATEGORY "
        + "FROM csvimport "
        + "WHERE csvimport.CSVERROR='New product' "
        + "ORDER BY csvimport.REFERENCE");

report.addField("reference", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("code", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("name", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("pricebuy", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("pricesell", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);
report.addField("category",com.mx.kylgis.pos.data.loader.Datas.STRING);

report;