//    uniCenta oPOS - touch friendly EPoS
//    Copyright (c) 2009-2018 uniCenta & previous Openbravo POS works
//    https://unicenta.com
//
//    This file is part of uniCenta oPOS
//
//    uniCenta oPOS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    uniCenta oPOS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with uniCenta oPOS.  If not, see <http://www.gnu.org/licenses/>.

report = new com.mx.kylgis.pos.reports.PanelReportBean();

report.setTitleKey("Menu.UserSells");
report.setReport("/com/openbravo/reports/users_voids");
report.setResourceBundle("com/openbravo/reports/users_messages");

report.setSentence("SELECT NAME, PRODUCTNAME, " +
        "REMOVEDDATE, " +
        "UNITS " +
        "FROM lineremoved " +
        "WHERE ?(QBF_FILTER) " +
        "ORDER BY NAME");

report.addParameter("REMOVEDDATE");
report.addParameter("REMOVEDDATE");

paramdates = new com.mx.kylgis.pos.reports.JParamsDatesInterval();
paramdates.setStartDate(com.mx.kylgis.pos.beans.DateUtils.getToday());
paramdates.setEndDate(com.mx.kylgis.pos.beans.DateUtils.getTodayMinutes());
report.addQBFFilter(paramdates);

report.addParameter("lineremoved.ID");
report.addParameter("lineremoved.NAME");
report.addQBFFilter(new com.mx.kylgis.pos.reports.JParamsUser());

report.addField("NAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("PRODUCTNAME", com.mx.kylgis.pos.data.loader.Datas.STRING);
report.addField("DATE", com.mx.kylgis.pos.data.loader.Datas.TIMESTAMP);
report.addField("UNITS", com.mx.kylgis.pos.data.loader.Datas.DOUBLE);

report;
