//    KylGis POS Punto de Venta Táctil
//    Copyright (c) 2026 KylGis POS
//    Portions Copyright (c) 2015-2021 John Lewis (Chromis POS / ChromisKitchenScreen)
//    Portions Copyright (c) 2010-2021 Hugh Clayson / uniCenta (https://unicenta.com)
//    Portions Copyright (c) 2006-2010 Adrián Romero / Openbravo S.L.
//
//    This file is part of KylGis POS
//
//    KylGis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    KylGis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with KylGis POS.  If not, see <http://www.gnu.org/licenses/>.
package com.mx.kylgis.pos.printer.screen;

import com.mx.kylgis.pos.printer.ticket.BasicTicket;
import java.awt.*;
import java.awt.font.FontRenderContext;
import java.awt.geom.AffineTransform;
import java.util.Map;

class JTicket extends javax.swing.JPanel {
    
    private static final int H_GAP = 8;
    private static final int V_GAP = 8;
    private final int columns;
    private final int lineWidth;
    
    private final BasicTicket basict;
    private final Map desktophints;
   
    /** Creates new form JTicket */
    public JTicket(BasicTicket t) {
        this(t, 42);
    }

    public JTicket(BasicTicket t, int columns) {
        basict = t;
        this.columns = Math.max(16, Math.min(columns, 120));
        this.lineWidth = calculateLineWidth(this.columns);
        desktophints = (Map) Toolkit.getDefaultToolkit().getDesktopProperty("awt.font.desktophints");
        initComponents();
    }
    
    private static int calculateLineWidth(int columns) {
        Font font = new Font("Monospaced", Font.PLAIN, 12)
                .deriveFont(AffineTransform.getScaleInstance(1.0, 1.40));
        FontRenderContext frc = new FontRenderContext(null, true, true);
        double charWidth = font.getStringBounds("M", frc).getWidth();
        // Two extra pixels avoid clipping caused by integer FontMetrics rounding.
        return (int) Math.ceil(charWidth * columns) + 2;
    }

    @Override
    protected void paintComponent(Graphics g) {
        paintBorder(g);
        
        Graphics2D g2d = (Graphics2D) g;

        if (desktophints != null) {
            g2d.addRenderingHints(desktophints);
        }
        
        Insets i = getInsets();
        g2d.setPaint(new GradientPaint(
                getWidth() - i.left - i.right - 100, 
                getHeight() - i.top - i.bottom - 100, 
                getBackground(), 
                getWidth() - i.left - i.right, 
                getHeight() - i.top - i.bottom, 
                new Color(0xf0f0f0), true));
        g2d.fillRect(i.left, i.top, 
                getWidth() - i.left - i.right, 
                getHeight() - i.top - i.bottom);
        
        g.setColor(getForeground());
        basict.draw(g2d, i.left + H_GAP, i.top + V_GAP, lineWidth);   
    }  
    
      
    @Override
    public Dimension getPreferredSize() {
        Insets ins = getInsets();
        return new Dimension((int) (
                lineWidth + 2 * H_GAP) + ins.left + ins.right
                  , (int) (basict.getHeight() + 2 * V_GAP) + ins.top + ins.bottom);
    }

    @Override
    public Dimension getMaximumSize() {
        return getPreferredSize();
    }

    @Override
    public Dimension getMinimumSize() {
        return getPreferredSize();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
